{% set name = "dash-mantine-components" %}
{% set version = "0.10.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_mantine_components-{{ version }}.tar.gz
  sha256: 5ec838653b856ae55869b7c661b7d74d2799c1259aa3ebaf57346c6a2f7282ea

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dash >=2.0.0
    - dash-core-components ==2.0.0
    - dash-html-components ==2.0.0
    - dash-table ==5.0.0

test:
  imports:
    - dash_mantine_components
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/snehilvj/dash-mantine-components
  summary: Custom dash components based on Mantine React Components library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: http://dash-mantine-components.herokuapp.com
  dev_url: https://github.com/snehilvj/dash-mantine-components

extra:
  recipe-maintainers:
    - snehilvj
