{% set name = "dash-mantine-components" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_mantine_components-{{ version }}.tar.gz
  sha256: c3dcbfd89813a1539654b8d016eb953dc5f67aafe1a77d45b5ec9faa6f25d3e7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - dash >=2.5.1

test:
  imports:
    - dash_mantine_components
    - dash_mantine_components.Card
    - dash_mantine_components.Image
    - dash_mantine_components.Center
    - dash_mantine_components.Tooltip

about:
  home: https://github.com/snehilvj/dash-mantine-components
  summary: Custom dash components based on Mantine React Components library
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://www.dash-mantine-components.com/
  dev_url: https://github.com/snehilvj/dash-mantine-components

extra:
  recipe-maintainers:
    - snehilvj
    - '0xbe7a'
