# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: yaml -*-

stages:
- stage: Check
  jobs:
    - job: Skip
      pool:
        vmImage: 'ubuntu-22.04'
      variables:
        DECODE_PERCENTS: 'false'
        RET: 'true'
      steps:
      - checkout: self
        fetchDepth: '2'
      - bash: |
          git_log=`git log --max-count=1 --skip=1 --pretty=format:"%B" | tr "\n" " "`
          echo "##vso[task.setvariable variable=log]$git_log"
        displayName: Obtain commit message
      - bash: echo "##vso[task.setvariable variable=RET]false"
<<<<<<< HEAD
        condition: or(contains(variables.log, '[skip azp]'), contains(variables.log, '[azp skip]'), contains(variables.log, '[skip ci]'), contains(variables.log, '[ci skip]'))
=======
        condition: and(eq(variables['Build.Reason'], 'PullRequest'), or(contains(variables.log, '[skip azp]'), contains(variables.log, '[azp skip]'), contains(variables.log, '[skip ci]'), contains(variables.log, '[ci skip]')))
>>>>>>> 17b9e30 (MNT: Re-rendered with conda-build 24.9.0, conda-smithy 3.44.0, and conda-forge-pinning 2024.11.05.21.36.17)
        displayName: Skip build?
      - bash: echo "##vso[task.setvariable variable=start_main;isOutput=true]$RET"
        name: result
        displayName: Export result
- stage: Build
  condition: and(succeeded(), eq(dependencies.Check.outputs['Skip.result.start_main'], 'true'))
  dependsOn: Check
  jobs:
    - template: ./.azure-pipelines/azure-pipelines-linux.yml